# Generated by Django 4.2.5 on 2023-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(default='NoImage.jpg', upload_to='')),
            ],
        ),
    ]
