# Generated by Django 4.2.5 on 2023-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_data',
            name='rating',
            field=models.FloatField(),
        ),
    ]
