# Generated by Django 4.2.5 on 2023-10-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_data_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Data',
            new_name='BookData',
        ),
    ]
